apiVersion: apps/v1

kind: Deployment

metadata:
  name: html-deploy
  labels:
    app: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      name: html-deploy
      labels:
        app: webserver
    spec:
      volumes:
        - name: html-pv
          persistentVolumeClaim:
            claimName: html-pv-claim
        
      containers:
        - name: html-deploy
          image: aaditya5/html:v1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: "/var/log/httpd"
              name: html-pv
